const actionTpye = {
    LOGIN_SUCESS : 'LOGIN_SUCCESS',
    LOGIN_FAIL : 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL : 'REGISTER_FAIL',
    LOGOUT : 'LOGOUT',
    LOVE_POST : 'LOVE_POST',
    DELETE_LOVE_POST  : 'DELETE_LOVE_POST',

    GET_POSTS : 'GET_POSTS',
    GET_POSTS_LIMIT : 'GET_POSTS_LIMIT',
    GET_POSTS_LIMIT_ADMIN : 'GET_POSTS_LIMIT_ADMIN',
    GET_NEW_POSTS : 'GET_NEW_POSTS',
    GET_OUSTANDING_POSTS : 'GET_OUSTANDING_POSTS',
    CHANGE_DATA_POST : 'CHANGE_DATA_POST' ,
    ISCHECK_POST : 'ISCHECK_POST',

    GET_TYPE_PACKAGE : 'GET_TYPE_POST',
    GET_TIME_PACKAGE : 'GET_TIME_PACKAGE',
    GET_NUMBER_PACKAGE : 'GET_NUMBER_PACKAGE',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES : 'GET_PRICES',
    GET_ACREAGE : 'GET_ACREAGE',
    GET_PROVINCE : 'GET_PROVINCE',

    GET_USER : 'GET_USER',
    GET_ADDRESS : 'GET_ADDESS'
}
export default actionTpye